version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      zookeeper-net:
        ipv4_address: 172.30.0.4
    restart: always
  dubboAdmin:
    image: apache/dubbo-admin
    container_name: dubboAdmin
    depends_on:
      - zookeeper
    environment:
      - admin.registry.address=zookeeper://zookeeper:2181
      - admin.config-center=zookeeper://zookeeper:2181
      - admin.metadata-report.address=zookeeper://zookeeper:2181
    ports:
      - "8080:8080"
    networks:
      zookeeper-net:
        ipv4_address: 172.30.0.5
    restart: always
networks:
  zookeeper-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
