version: "3"
services:
  dubbo-zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: dubbo-zookeeper
    ports:
      - "2181:2181"
    networks:
      zookeeper-net:
        ipv4_address: 172.30.0.4
    restart: always
  dubbo-admin:
    image: apache/dubbo-admin
    container_name: dubbo-admin
    depends_on:
      - dubbo-zookeeper
    environment:
      - admin.registry.address=zookeeper://dubbo-zookeeper:2181
      - admin.config-center=zookeeper://dubbo-zookeeper:2181
      - admin.metadata-report.address=zookeeper://dubbo-zookeeper:2181
    ports:
      - "18080:8080"
    networks:
      zookeeper-net:
        ipv4_address: 172.30.0.5
    restart: always
networks:
  zookeeper-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16


